models:
  download_url: https://huggingface.co/stabilityai/stable-diffusion-2-1-base/resolve/main/v2-1_512-ema-pruned.ckpt
  original_path: "./models/v2-1-pruned-ema.ckpt"
  control_path: "./models/control_v2-1_ini.ckpt"
  cldm_path: "./models/cldm_v21.yaml"
  last_path: "./models/ckeckpoints/last.ckpt"

dataset:
  images_dir: "./data/images/"
  annotations_path: "./data/prompt.json"
  coco_path: "./data/captions_train2017.json"

training:
  model:
    sd_locked: True
    only_mid_control: False
  dataloader:
    batch_size: 16
    dataloader_workers: 4
    learning_rate: 1e-4
  trainer: 
    precision: 16
    accumulate_grad_batches: 4
    accelerator: 'gpu'
    gpus: 1
    max_steps: 10000

callbacks:
  model_checkpoint:
    every_n_train_steps: 3000
    dirpath: './models/ckeckpoints/'
    save_last: True
    save_weights_only: False
    save_top_k: 3
    monitor: 'train/loss'


wandb:
  use: True
  project_name: "Diffusar"
  name: "ControlNet-SD2.1"
  log_model: True
  log: "all"
  log_freq: 300

misc:
  image_size: 512
  saving_memory: False
