models:
  download_url: https://huggingface.co/stabilityai/stable-diffusion-2-1-base/resolve/main/v2-1_512-ema-pruned.ckpt
  original_path: "./models/v2-1-pruned-ema.ckpt"
  control_path: "./models/control_v2-1_ini.ckpt"
  cldm_path: "./models/cldm_v21.yaml"
  final_path: "./models/final_model.pt"

dataset:
  images_dir: "./data/images/"
  annotations_path: "./data/prompt.json"
  coco_path: "./data/captions_val2014.json"

training:
  batch_size: 16
  learning_rate: 1e-5
  sd_locked: True
  only_mid_control: False
  precision: 16
  accumulate_grad_batches: 4
  dataloader_workers: 1

callbacks:
  model_checkpoint:
    ckpt_freq: 10
    ckpt_dir: './models/ckeckpoints/'
    logger_freq: 300
    save_last: True
    save_weight_only: False
    save_top_k: 3
    monitor: 'train/loss'
  early_stopping:
    monitor: 'train/loss'
    patience: 50


wandb:
  use: True
  project_name: "Diffusar"
  name: "ControlNet-SD2.1"
  log_model: True
  log: "all"

misc:
  image_size: 512
