paths:
  save_path: './models/checkpoints/' #Need to be added
  load_path: './models/checkpoints/last.ckpt'

dataset:
  images_dir: "./data/images/"
  annotations_path: "./data/prompt.json"
  
  coco_path: "./data/captions_train2017.json"

training:
  model_config_path: './models/model_config.yaml'
  task: 'Restoration'
  dataloader:
    batch_size: 16
    dataloader_workers: 8
    learning_rate: 0.0001 #1e-4
  trainer: 
    precision: 32
    # accumulate_grad_batches: 1
    accelerator: 'gpu'
    gpus: 1
    max_steps: -1
    max_epochs: 100
    limit_val_batches: 0
callbacks:
  model_checkpoint:
    every_n_train_steps: 1000
    dirpath: './models/ckeckpoints/'
    save_last: True
    save_weights_only: False
    save_top_k: 3
    monitor: 'train/loss'

wandb:
  use: True
  project_name: "Diffusar"
  name: "Palette"
  log_model: True
  log: "all"
  log_freq: 50

misc:
  image_size: 512
  seed: 42