paths:
  save_path: './models/checkpoints/'
  load_path: './models/checkpoints/'

dataset:
  images_dir: "./data/images/"
  annotations_path: "./data/prompt.json"
  coco_path: "./data/captions_train2017.json"

training:
  model_config_path: './models/model_config.yaml'
  training_args:
    max_epochs: 100
    max_steps: 100
    save_every_n_checkpoints: 10
    val_every_n_checkpoints: 10
    task: 'Restoration'
    sample_num: 8
  dataloader:
    batch_size: 16
    dataloader_workers: 4
    learning_rate: 0.0001 #1e-4
  trainer: 
    precision: 16
    accumulate_grad_batches: 4
    accelerator: 'gpu'
    gpus: 1
    max_steps: 10000

callbacks:
  model_checkpoint:
    every_n_train_steps: 3000
    dirpath: './models/ckeckpoints/'
    save_last: True
    save_weights_only: False
    save_top_k: 3
    monitor: 'train/loss'


wandb:
  use: True
  project_name: "Diffusar"
  name: "Palette"
  log_model: True
  log: "all"
  log_freq: 300

misc:
  image_size: 512
  seed: 42