unet_args:
  'image_size': 224
  'in_channel': 6
  'inner_channel': 64
  'out_channel': 3
  'res_blocks': 2
  'attn_res': [16]
  'dropout' : 0.2
  'channel_mults' : [1, 2, 4, 8]
  'conv_resample' : True
  'use_checkpoint' : False
  'use_fp16' : False
  'num_heads' : 1
  'num_head_channels' : 32
  'num_heads_upsample' : -1
  'use_scale_shift_norm' : True
  'resblock_updown' : True
  'use_new_attention_order' : False

scheduler_args:
  "schedule": "linear"
  "n_timestep": 2000
  "linear_start": 1e-6
  "linear_end": 0.01

ema_scheduler_args:
  "ema_start": 1
  "ema_iter": 1
  "ema_decay": 0.9999

optimizer_args:
  "lr": 5e-5
  "weight_decay": 0

paths:
  save_path: str
  save_path_ema: str
  load_path: str
  load_path_ema: str
  # in format of '*folder/{epoch}.state'
  state_save_path: str

training:
  batch_size: int
  max_epochs: int
  max_steps: int
  save_every_n_checkpoints: int
  val_every_n_checkpoints: int
  task: 'Restoration'
  device: 'gpu'
  sample_num: 8

seed: 42